### ISSUE TITLE
Can't pay with openpay

### ISSUE THREAD

**Issue by ashekelahe** [FMarcelFC/openpay_bbva#4]
There are no examples of how to pay.

**Is this function okay?**

Future<void> makePayment(double amount, int orderID, UserInfoModel customer, String token, String sessionID) async {
    String url = '${AppConstants.isLiveMode ? 'https://api.openpay.pe' : 'https://sandbox-api.openpay.pe'}/v1/${AppConstants.merchantId}/charges';
    Map<String, dynamic> data = {
      'source_id': token,
      'amount': amount,
      'currency': 'PEN',
      'description': orderID.toString(),
      'order_id': orderID.toString(),
      'device_session_id': sessionID,
      'customer': {
        'name': customer.fName,
        'last_name': customer.lName,
        'phone_number': customer.phone,
        'email': customer.email
      }
    };
    print('Body:=====> $data');
    http.Response response = await http.post(Uri.parse(url), body: jsonEncode(data), headers: {'Content-type': 'application/json', 'Authorization': 'Bearer ${AppConstants.secretApiKey}'});
    print('Response:=====> ${response.body}');
  }

**Response:**
flutter: Body:=====> {source_id: kqzsmwizsr6zuxghrsx6, amount: 100.0, currency: PEN, description: 100001, order_id: 100001, device_session_id: 5E24EAFD0353S7BB82A399CD96D19D5C, customer: {name: AShek, last_name: Elahe, phone_number: +8801879762951, email: ashek@6amtech.com}}
flutter: Response:=====> {"http_code":401,"error_code":1002,"category":"request","description":"The api key or merchant id are invalid"}

**Comment by FMarcelFC** [comment]
I have the same implementation as you, the only difference that I see is that I send the JSON request to a PHP file in our server, for internal authentication and authorization, instead of sending it directly to the Openpay Endpoint. I don't know how can I help you since my implementation from the app is the same as yours.

**Comment by ashekelahe** [comment]
Can you share your implementation please from flutter code? @FMarcelFC

**Comment by FMarcelFC** [comment]
Here is my implementation @ashekelahe 
`
Future<ServerResponse> pagoTarjeta(
      String cardNumber,
      String expires,
      String cvv,
      String name,
      num amount,
      String description,
      String referencia,
      String email) async {
    final fechaSeparada = expires.split('/');
    final nombreSeparado = name.split(' ');
    final String? token = await openpay.getCardToken(
        name, cardNumber, fechaSeparada[0], fechaSeparada[1], cvv);
    final String? deviceId = await openpay.getDeviceID();

    final url = Uri.parse('<<INTERNAL_SERVER_URL>>');
    final headers = <String, String>{
      'Content-Type': 'application/json',
    };
    final Map<String, dynamic> req = {
      'source_id': token,
      'method': 'card',
      'amount': amount,
      'currency': 'MXN',
      'description': description,
      'order_id': referencia,
      'device_session_id': deviceId,
      'customer': {
        'name': nombreSeparado[0],
        'last_name': nombreSeparado.length == 2
            ? nombreSeparado[1]
            : formatearNombre(nombreSeparado),
        'email': email
      }
    };
    try {
      final response =
          await http.post(url, headers: headers, body: jsonEncode(req));
      if (response.statusCode == 500) {
        throw Exception('Error interno de servidor');
      } else {
        final result = ServerResponse(error: false, data: response.body);
        return result;
      }
    } catch (e) {
      final ServerResponse result =
          ServerResponse(error: true, data: e.toString());
      return result;
    }
  }`

**Comment by ashekelahe** [comment]
@FMarcelFC 
Can you please share the integration from backend?
