### ISSUE TITLE
Spain support

### ISSUE THREAD

**Issue by EliaTolin** [FMarcelFC/openpay_bbva#5]
Hello, 
Does this package support spain?
Does it change anything? 
Is it possible to integrate it?

**Comment by FMarcelFC** [comment]
Hello @EliaTolin, this package uses the Openpay API, which has 3 API Endpoints (to my knowledge):
- [México](https://api.openpay.mx/)
- [Perú](https://api.openpay.pe/)
- [Colombia](https://api.openpay.co/)

They would need to add an API Endpoint for Spain transactions, so I can update the package.
